### ISSUE TITLE
Error getting the values parsed in ticker

### ISSUE THREAD

**Issue by mariobrosch** [BarRaider/streamdeck-stockticker#16]
Got this error in the logfile:
2019-09-12 15:30:20.7414|ERROR|BarRaider.SdTools.Logger|OnTick Exception: Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Double'. Path 'PHG.quote.open', line 1, position 152. ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at BarRaider.StockTicker.StockComm.<GetSymbol>d__8.MoveNext() in E:\Projects\GitHub\streamdeck-stockticker\streamdeck-stockticker\BarRaider.StockTicker\StockComm.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StockTicker.SymbolTicker.<OnTick>d__19.MoveNext() in E:\Projects\GitHub\streamdeck-stockticker\streamdeck-stockticker\SymbolTicker.cs:line 130

**Comment by BarRaider** [comment]
[Fixed in newer version but forgot to close issue]
